// ============================================
// MyTrackify — Mock Data
// Realistic sample data for development
// ============================================

import type {
  Company,
  InterviewProcess,
  InterviewExperience,
  ApplicationJourney,
  StudentProfile,
  DashboardStats,
  ReadinessAnalysis,
  RoundStats,
} from '../types';

// --- Current User Profile ---
export const currentUser: StudentProfile = {
  id: 1,
  email: 'student@college.edu',
  collegeId: 'CS2025042',
  graduationYear: 2025,
  branch: 'Computer Science & Engineering',
  cgpaRange: '8.0-8.5',
  anonymizedId: 'STUDENT_4A7F3B2E',
  leetcodeCount: 280,
  leetcodeEasy: 80,
  leetcodeMedium: 160,
  leetcodeHard: 40,
  contestRating: 1450,
  skillVector: [0.3, 0.7, 0.4, 0.8, 0.5], // DP, Graphs, Trees, Arrays, Strings
  createdAt: '2024-06-15T10:00:00Z',
  lastLogin: '2025-04-19T08:30:00Z',
  isActive: true,
  totalApplications: 12,
  offersReceived: 3,
  successRate: 25.0,
  sectorsApplied: ['Product', 'Service', 'Trading'],
  lastApplicationDate: '2025-03-20',
};

// --- Companies ---
export const companies: Company[] = [
  {
    id: 1,
    name: 'Google',
    sector: 'Product',
    headquartersLocation: 'Bangalore, India',
    website: 'https://careers.google.com',
    visitFrequency: 'Annual',
    typicalRoles: ['SDE', 'STEP Intern', 'ML Engineer'],
    avgCtcRange: '18-22 LPA',
    totalApplications: 47,
    totalOffers: 6,
    avgSuccessRate: 12.7,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-03-15T00:00:00Z',
  },
  {
    id: 2,
    name: 'Microsoft',
    sector: 'Product',
    headquartersLocation: 'Hyderabad, India',
    website: 'https://careers.microsoft.com',
    visitFrequency: 'Annual',
    typicalRoles: ['SDE', 'PM', 'Data Scientist'],
    avgCtcRange: '16-20 LPA',
    totalApplications: 52,
    totalOffers: 10,
    avgSuccessRate: 19.2,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-03-10T00:00:00Z',
  },
  {
    id: 3,
    name: 'Amazon',
    sector: 'Product',
    headquartersLocation: 'Bangalore, India',
    website: 'https://www.amazon.jobs',
    visitFrequency: 'Bi-Annual',
    typicalRoles: ['SDE', 'SDE Intern', 'Business Analyst'],
    avgCtcRange: '14-18 LPA',
    totalApplications: 63,
    totalOffers: 15,
    avgSuccessRate: 23.8,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-02-28T00:00:00Z',
  },
  {
    id: 4,
    name: 'Goldman Sachs',
    sector: 'Trading',
    headquartersLocation: 'Bangalore, India',
    website: 'https://www.goldmansachs.com/careers',
    visitFrequency: 'Annual',
    typicalRoles: ['Analyst', 'Engineering Analyst'],
    avgCtcRange: '20-28 LPA',
    totalApplications: 38,
    totalOffers: 5,
    avgSuccessRate: 13.2,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-03-01T00:00:00Z',
  },
  {
    id: 5,
    name: 'Flipkart',
    sector: 'Product',
    headquartersLocation: 'Bangalore, India',
    website: 'https://www.flipkartcareers.com',
    visitFrequency: 'Annual',
    typicalRoles: ['SDE', 'Data Analyst'],
    avgCtcRange: '14-17 LPA',
    totalApplications: 45,
    totalOffers: 12,
    avgSuccessRate: 26.7,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-02-15T00:00:00Z',
  },
  {
    id: 6,
    name: 'Deloitte',
    sector: 'Consulting',
    headquartersLocation: 'Mumbai, India',
    website: 'https://www2.deloitte.com/careers',
    visitFrequency: 'Bi-Annual',
    typicalRoles: ['Analyst', 'Consultant', 'Technology Analyst'],
    avgCtcRange: '8-12 LPA',
    totalApplications: 72,
    totalOffers: 25,
    avgSuccessRate: 34.7,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-03-05T00:00:00Z',
  },
  {
    id: 7,
    name: 'Infosys',
    sector: 'Service',
    headquartersLocation: 'Bangalore, India',
    website: 'https://www.infosys.com/careers',
    visitFrequency: 'Annual',
    typicalRoles: ['Systems Engineer', 'Specialist Programmer'],
    avgCtcRange: '4-8 LPA',
    totalApplications: 120,
    totalOffers: 65,
    avgSuccessRate: 54.2,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-01-20T00:00:00Z',
  },
  {
    id: 8,
    name: 'Adobe',
    sector: 'Product',
    headquartersLocation: 'Noida, India',
    website: 'https://www.adobe.com/careers',
    visitFrequency: 'Annual',
    typicalRoles: ['SDE', 'MTS', 'Research Engineer'],
    avgCtcRange: '18-25 LPA',
    totalApplications: 35,
    totalOffers: 4,
    avgSuccessRate: 11.4,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-03-12T00:00:00Z',
  },
  {
    id: 9,
    name: 'JP Morgan Chase',
    sector: 'Trading',
    headquartersLocation: 'Mumbai, India',
    website: 'https://careers.jpmorgan.com',
    visitFrequency: 'Annual',
    typicalRoles: ['Technology Analyst', 'Quant Analyst'],
    avgCtcRange: '15-22 LPA',
    totalApplications: 42,
    totalOffers: 8,
    avgSuccessRate: 19.0,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-02-25T00:00:00Z',
  },
  {
    id: 10,
    name: 'TCS',
    sector: 'Service',
    headquartersLocation: 'Mumbai, India',
    website: 'https://www.tcs.com/careers',
    visitFrequency: 'Annual',
    typicalRoles: ['Systems Engineer', 'Digital Specialist'],
    avgCtcRange: '3.5-7 LPA',
    totalApplications: 150,
    totalOffers: 90,
    avgSuccessRate: 60.0,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-01-10T00:00:00Z',
  },
  {
    id: 11,
    name: 'Uber',
    sector: 'Product',
    headquartersLocation: 'Hyderabad, India',
    website: 'https://www.uber.com/careers',
    visitFrequency: 'Once',
    typicalRoles: ['SDE-I', 'Backend Engineer'],
    avgCtcRange: '20-26 LPA',
    totalApplications: 28,
    totalOffers: 3,
    avgSuccessRate: 10.7,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-03-18T00:00:00Z',
  },
  {
    id: 12,
    name: 'Wipro',
    sector: 'Service',
    headquartersLocation: 'Bangalore, India',
    website: 'https://careers.wipro.com',
    visitFrequency: 'Annual',
    typicalRoles: ['Project Engineer', 'Turbo Engineer'],
    avgCtcRange: '3.5-6.5 LPA',
    totalApplications: 130,
    totalOffers: 78,
    avgSuccessRate: 60.0,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-01-25T00:00:00Z',
  },
];

// --- Interview Processes ---
export const interviewProcesses: InterviewProcess[] = [
  {
    id: 1,
    companyId: 1,
    academicYear: '2024-25',
    semester: 'Fall',
    rounds: [
      { roundNumber: 1, roundType: 'Online Assessment', topics: ['DSA', 'Aptitude'], durationMinutes: 90, avgEliminationRate: 68 },
      { roundNumber: 2, roundType: 'Technical Interview', topics: ['DSA', 'System Design'], durationMinutes: 45, avgEliminationRate: 55 },
      { roundNumber: 3, roundType: 'Hiring Manager', topics: ['Behavioral', 'Culture Fit'], durationMinutes: 30, avgEliminationRate: 25 },
    ],
    verifiedCount: 12,
    lastVerifiedAt: '2025-02-10T00:00:00Z',
    isCurrent: true,
  },
  {
    id: 2,
    companyId: 2,
    academicYear: '2024-25',
    semester: 'Fall',
    rounds: [
      { roundNumber: 1, roundType: 'Online Assessment', topics: ['DSA', 'MCQs'], durationMinutes: 75, avgEliminationRate: 62 },
      { roundNumber: 2, roundType: 'Technical Interview 1', topics: ['DSA', 'Problem Solving'], durationMinutes: 60, avgEliminationRate: 45 },
      { roundNumber: 3, roundType: 'Technical Interview 2', topics: ['System Design', 'CS Fundamentals'], durationMinutes: 60, avgEliminationRate: 40 },
      { roundNumber: 4, roundType: 'HR Interview', topics: ['Behavioral', 'Culture Fit'], durationMinutes: 30, avgEliminationRate: 15 },
    ],
    verifiedCount: 18,
    lastVerifiedAt: '2025-01-20T00:00:00Z',
    isCurrent: true,
  },
  {
    id: 3,
    companyId: 3,
    academicYear: '2024-25',
    semester: 'Fall',
    rounds: [
      { roundNumber: 1, roundType: 'Online Assessment', topics: ['DSA', 'Logical Reasoning'], durationMinutes: 90, avgEliminationRate: 70 },
      { roundNumber: 2, roundType: 'Technical Interview', topics: ['DSA', 'Leadership Principles'], durationMinutes: 60, avgEliminationRate: 50 },
      { roundNumber: 3, roundType: 'Bar Raiser Interview', topics: ['System Design', 'Behavioral'], durationMinutes: 45, avgEliminationRate: 35 },
    ],
    verifiedCount: 22,
    lastVerifiedAt: '2025-02-05T00:00:00Z',
    isCurrent: true,
  },
  {
    id: 4,
    companyId: 4,
    academicYear: '2024-25',
    semester: 'Fall',
    rounds: [
      { roundNumber: 1, roundType: 'Online Assessment', topics: ['DSA', 'Mathematics', 'CS Fundamentals'], durationMinutes: 120, avgEliminationRate: 75 },
      { roundNumber: 2, roundType: 'Technical Interview', topics: ['DSA', 'OOP', 'Database'], durationMinutes: 60, avgEliminationRate: 50 },
      { roundNumber: 3, roundType: 'Hiring Manager', topics: ['Behavioral', 'Puzzles'], durationMinutes: 45, avgEliminationRate: 20 },
    ],
    verifiedCount: 8,
    lastVerifiedAt: '2025-01-15T00:00:00Z',
    isCurrent: true,
  },
  {
    id: 5,
    companyId: 5,
    academicYear: '2024-25',
    semester: 'Fall',
    rounds: [
      { roundNumber: 1, roundType: 'Online Assessment', topics: ['DSA', 'Aptitude'], durationMinutes: 90, avgEliminationRate: 65 },
      { roundNumber: 2, roundType: 'Machine Coding', topics: ['System Design', 'OOP'], durationMinutes: 90, avgEliminationRate: 55 },
      { roundNumber: 3, roundType: 'Technical Interview', topics: ['DSA', 'Problem Solving'], durationMinutes: 45, avgEliminationRate: 35 },
      { roundNumber: 4, roundType: 'HR Interview', topics: ['Behavioral'], durationMinutes: 30, avgEliminationRate: 10 },
    ],
    verifiedCount: 15,
    lastVerifiedAt: '2025-02-20T00:00:00Z',
    isCurrent: true,
  },
];

// --- Interview Experiences ---
export const interviewExperiences: InterviewExperience[] = [
  {
    id: 1,
    attemptId: 1,
    questionsAsked: '1. Longest substring without repeating characters (Medium)\n2. Design LRU Cache (Hard)\n3. Aptitude: Probability questions — conditional probability, Bayes theorem applications',
    topics: ['Strings', 'Hash Maps', 'Design'],
    interviewerFocus: 'Time complexity analysis and space optimization',
    preparationTips: 'Focus on Sliding Window technique. Time management crucial — 90 mins for 3 coding + 10 aptitude. Practice on HackerEarth IDE specifically, it\'s different from LeetCode.',
    difficultyRating: 4,
    helpfulCount: 23,
    verified: true,
    createdAt: '2024-09-15T00:00:00Z',
    updatedAt: '2024-09-15T00:00:00Z',
    studentAnonymizedId: 'STUDENT_4A7F',
    roundNumber: 1,
    roundType: 'Online Assessment',
    companyName: 'Google',
    outcome: 'Passed',
  },
  {
    id: 2,
    attemptId: 2,
    questionsAsked: 'Started with Trees problem — Find LCA in BST. Then asked to design a URL shortener with scaling considerations. Follow-up: How would you handle 1 billion URLs? Sharding strategies?',
    topics: ['Trees', 'System Design', 'Databases'],
    interviewerFocus: 'Trade-off analysis and scalability thinking',
    preparationTips: 'Interviewer cared more about explaining trade-offs than perfect solution. Should have discussed sharding strategies more. Draw diagrams — they love visual explanations.',
    difficultyRating: 5,
    helpfulCount: 31,
    verified: true,
    createdAt: '2024-09-16T00:00:00Z',
    updatedAt: '2024-09-16T00:00:00Z',
    studentAnonymizedId: 'STUDENT_8B2C',
    roundNumber: 2,
    roundType: 'Technical Interview',
    companyName: 'Google',
    outcome: 'Failed',
  },
  {
    id: 3,
    attemptId: 3,
    questionsAsked: '4 coding questions in 75 mins:\n1. Two Sum variant (Easy)\n2. Valid Parentheses with custom brackets (Medium)\n3. Merge K sorted lists (Hard)\n4. MCQs on OS concepts (15 questions)',
    topics: ['Arrays', 'Stacks', 'Linked Lists', 'OS'],
    interviewerFocus: 'Speed and accuracy',
    preparationTips: 'Microsoft OA is on Codility. Their IDE autocomplete is broken — practice without it. MCQs are tricky: virtual memory, page replacement algorithms, deadlock conditions.',
    difficultyRating: 3,
    helpfulCount: 45,
    verified: true,
    createdAt: '2024-10-02T00:00:00Z',
    updatedAt: '2024-10-02T00:00:00Z',
    studentAnonymizedId: 'STUDENT_2D9E',
    roundNumber: 1,
    roundType: 'Online Assessment',
    companyName: 'Microsoft',
    outcome: 'Passed',
  },
  {
    id: 4,
    attemptId: 4,
    questionsAsked: 'Binary tree level order traversal. Then extended to zigzag traversal. Then asked to serialize and deserialize the tree. Very standard but interviewer expected clean, bug-free code.',
    topics: ['Trees', 'BFS', 'Serialization'],
    interviewerFocus: 'Code quality, edge cases',
    preparationTips: 'Microsoft interviewers want CLEAN code. Use meaningful variable names, handle null checks. They give hints — take them. Practice thinking out loud.',
    difficultyRating: 3,
    helpfulCount: 38,
    verified: true,
    createdAt: '2024-10-05T00:00:00Z',
    updatedAt: '2024-10-05T00:00:00Z',
    studentAnonymizedId: 'STUDENT_5F1A',
    roundNumber: 2,
    roundType: 'Technical Interview 1',
    companyName: 'Microsoft',
    outcome: 'Passed',
  },
  {
    id: 5,
    attemptId: 5,
    questionsAsked: 'Design a parking lot system. Then went deep into SOLID principles. Asked about strategy pattern usage. Then designed notification service architecture for ride-sharing app.',
    topics: ['System Design', 'OOP', 'Design Patterns'],
    interviewerFocus: 'Object-oriented design, extensibility',
    preparationTips: 'Read "Head First Design Patterns" — at least Strategy, Observer, Factory. Microsoft Round 2 is all about LLD. Use class diagrams. They love the SOLID explanation.',
    difficultyRating: 4,
    helpfulCount: 52,
    verified: true,
    createdAt: '2024-10-06T00:00:00Z',
    updatedAt: '2024-10-06T00:00:00Z',
    studentAnonymizedId: 'STUDENT_5F1A',
    roundNumber: 3,
    roundType: 'Technical Interview 2',
    companyName: 'Microsoft',
    outcome: 'Passed',
  },
  {
    id: 6,
    attemptId: 6,
    questionsAsked: '2 DSA questions + 1 Work simulation:\n1. Minimum cost to connect ropes (Greedy/Heaps)\n2. Find all anagrams in string\n3. Debugging a flawed inventory system — find 3 bugs in 20 mins',
    topics: ['Heaps', 'Strings', 'Debugging'],
    interviewerFocus: 'Leadership Principles — "Customer Obsession", "Bias for Action"',
    preparationTips: 'Amazon OA has a "Work Simulation" section — practice leadership principle scenarios. For coding, focus on Greedy and Heap problems. Their OA platform is Amazon SDE portal.',
    difficultyRating: 4,
    helpfulCount: 67,
    verified: true,
    createdAt: '2024-08-20T00:00:00Z',
    updatedAt: '2024-08-20T00:00:00Z',
    studentAnonymizedId: 'STUDENT_7C3D',
    roundNumber: 1,
    roundType: 'Online Assessment',
    companyName: 'Amazon',
    outcome: 'Passed',
  },
  {
    id: 7,
    attemptId: 7,
    questionsAsked: 'Started with "Tell me about a time you disagreed with a teammate." Then coding: implement a rate limiter. Then: design the backend for a food delivery app. Heavy focus on database schema.',
    topics: ['System Design', 'Rate Limiting', 'Databases', 'Behavioral'],
    interviewerFocus: 'Leadership Principles woven into technical questions',
    preparationTips: 'STAR method is mandatory for behavioral. For system design, Amazon loves discussing DynamoDB vs relational. Mention CAP theorem. They expect you to discuss monitoring and error handling.',
    difficultyRating: 5,
    helpfulCount: 41,
    verified: false,
    createdAt: '2024-08-22T00:00:00Z',
    updatedAt: '2024-08-22T00:00:00Z',
    studentAnonymizedId: 'STUDENT_9A4B',
    roundNumber: 2,
    roundType: 'Technical Interview',
    companyName: 'Amazon',
    outcome: 'Passed',
  },
  {
    id: 8,
    attemptId: 8,
    questionsAsked: 'Aptitude (30 questions, 50 mins): Quant heavy — permutations, time/distance, work problems. Coding (3 questions, 70 mins): Matrix rotation, longest palindromic substring, graph BFS shortest path. CS MCQs: DBMS normalization, SQL queries.',
    topics: ['Aptitude', 'Matrices', 'Strings', 'Graphs', 'DBMS'],
    interviewerFocus: 'Breadth of knowledge',
    preparationTips: 'Goldman OA is the longest at 120 mins — stamina matters. Aptitude is IndiaBIX level but harder. CS MCQs include tricky SQL output questions. Practice on HackerRank.',
    difficultyRating: 4,
    helpfulCount: 29,
    verified: true,
    createdAt: '2024-09-10T00:00:00Z',
    updatedAt: '2024-09-10T00:00:00Z',
    studentAnonymizedId: 'STUDENT_3E6F',
    roundNumber: 1,
    roundType: 'Online Assessment',
    companyName: 'Goldman Sachs',
    outcome: 'Passed',
  },
  {
    id: 9,
    attemptId: 9,
    questionsAsked: 'Online test with 3 sections: Logical reasoning, coding (2 medium DSA), English comprehension. Coding was easy compared to product companies. Focus was on clean code and following instructions.',
    topics: ['DSA', 'Logical Reasoning', 'English'],
    interviewerFocus: 'Following instructions, code readability',
    preparationTips: 'Deloitte test is easier than product companies but they care about code readability A LOT. Use proper naming conventions. English section is pass/fail — don\'t spend too much time.',
    difficultyRating: 2,
    helpfulCount: 15,
    verified: true,
    createdAt: '2024-11-05T00:00:00Z',
    updatedAt: '2024-11-05T00:00:00Z',
    studentAnonymizedId: 'STUDENT_1B8D',
    roundNumber: 1,
    roundType: 'Online Assessment',
    companyName: 'Deloitte',
    outcome: 'Passed',
  },
  {
    id: 10,
    attemptId: 10,
    questionsAsked: 'Machine coding round: Build a simplified Splitwise in 90 minutes. Should support adding expenses, splitting among users, and showing balances. Used OOP principles.',
    topics: ['Machine Coding', 'OOP', 'System Design'],
    interviewerFocus: 'Code organization, design patterns, extensibility',
    preparationTips: 'Flipkart machine coding is THE hardest part. Practice building mini-projects in 90 mins: parking lot, movie booking, split-wise. Use factory pattern, strategy pattern. Write tests if you have time — huge bonus.',
    difficultyRating: 5,
    helpfulCount: 72,
    verified: true,
    createdAt: '2024-10-15T00:00:00Z',
    updatedAt: '2024-10-15T00:00:00Z',
    studentAnonymizedId: 'STUDENT_6G2H',
    roundNumber: 2,
    roundType: 'Machine Coding',
    companyName: 'Flipkart',
    outcome: 'Passed',
  },
];

// --- Application Journeys (current user's) ---
export const userJourneys: ApplicationJourney[] = [
  {
    id: 1, studentId: 1, processId: 1,
    applicationType: 'On-Campus', applicationDate: '2024-09-10',
    finalOutcome: 'Rejected', finalRoundReached: 2,
    compensationOffered: null, roleOffered: null,
    createdAt: '2024-09-10T00:00:00Z', updatedAt: '2024-09-20T00:00:00Z',
    companyName: 'Google', companySector: 'Product',
  },
  {
    id: 2, studentId: 1, processId: 2,
    applicationType: 'On-Campus', applicationDate: '2024-10-01',
    finalOutcome: 'Selected', finalRoundReached: 4,
    compensationOffered: 18.5, roleOffered: 'SDE',
    createdAt: '2024-10-01T00:00:00Z', updatedAt: '2024-10-15T00:00:00Z',
    companyName: 'Microsoft', companySector: 'Product',
  },
  {
    id: 3, studentId: 1, processId: 3,
    applicationType: 'On-Campus', applicationDate: '2024-08-15',
    finalOutcome: 'Selected', finalRoundReached: 3,
    compensationOffered: 16.0, roleOffered: 'SDE',
    createdAt: '2024-08-15T00:00:00Z', updatedAt: '2024-08-25T00:00:00Z',
    companyName: 'Amazon', companySector: 'Product',
  },
  {
    id: 4, studentId: 1, processId: 4,
    applicationType: 'On-Campus', applicationDate: '2024-09-05',
    finalOutcome: 'Rejected', finalRoundReached: 1,
    compensationOffered: null, roleOffered: null,
    createdAt: '2024-09-05T00:00:00Z', updatedAt: '2024-09-08T00:00:00Z',
    companyName: 'Goldman Sachs', companySector: 'Trading',
  },
  {
    id: 5, studentId: 1, processId: 5,
    applicationType: 'On-Campus', applicationDate: '2024-10-10',
    finalOutcome: 'Selected', finalRoundReached: 4,
    compensationOffered: 15.0, roleOffered: 'SDE',
    createdAt: '2024-10-10T00:00:00Z', updatedAt: '2024-10-25T00:00:00Z',
    companyName: 'Flipkart', companySector: 'Product',
  },
  {
    id: 6, studentId: 1, processId: 6,
    applicationType: 'Off-Campus', applicationDate: '2025-01-15',
    finalOutcome: 'In Progress', finalRoundReached: null,
    compensationOffered: null, roleOffered: null,
    createdAt: '2025-01-15T00:00:00Z', updatedAt: '2025-01-15T00:00:00Z',
    companyName: 'Uber', companySector: 'Product',
  },
];

// --- Dashboard Stats ---
export const dashboardStats: DashboardStats = {
  totalApplications: 12,
  totalOffers: 3,
  successRate: 25.0,
  companiesExplored: 8,
  experiencesLogged: 6,
  recentActivity: [
    { id: 1, type: 'offer', title: 'Offer from Microsoft', subtitle: 'SDE — 18.5 LPA', timestamp: '2024-10-15', icon: '🎉' },
    { id: 2, type: 'experience', title: 'Logged Google Round 2', subtitle: 'Technical Interview — Difficulty 5/5', timestamp: '2024-09-16', icon: '📝' },
    { id: 3, type: 'application', title: 'Applied to Uber', subtitle: 'Off-Campus — In Progress', timestamp: '2025-01-15', icon: '📤' },
    { id: 4, type: 'offer', title: 'Offer from Flipkart', subtitle: 'SDE — 15 LPA', timestamp: '2024-10-25', icon: '🎉' },
    { id: 5, type: 'application', title: 'Applied to Goldman Sachs', subtitle: 'On-Campus — Rejected at OA', timestamp: '2024-09-08', icon: '📤' },
  ],
  applicationsByMonth: [
    { name: 'Aug', value: 2 },
    { name: 'Sep', value: 4 },
    { name: 'Oct', value: 3 },
    { name: 'Nov', value: 1 },
    { name: 'Dec', value: 0 },
    { name: 'Jan', value: 2 },
  ],
  outcomeDistribution: [
    { name: 'Selected', value: 3, color: '#10b981' },
    { name: 'Rejected', value: 5, color: '#f43f5e' },
    { name: 'In Progress', value: 2, color: '#6366f1' },
    { name: 'Withdrew', value: 2, color: '#64748b' },
  ],
};

// --- Round Stats (for company detail) ---
export const companyRoundStats: Record<number, RoundStats[]> = {
  1: [ // Google
    { roundNumber: 1, roundType: 'Online Assessment', totalAttempts: 47, passedCount: 15, failedCount: 32, eliminationRate: 68, avgDifficulty: 4.1 },
    { roundNumber: 2, roundType: 'Technical Interview', totalAttempts: 15, passedCount: 7, failedCount: 8, eliminationRate: 53, avgDifficulty: 4.6 },
    { roundNumber: 3, roundType: 'Hiring Manager', totalAttempts: 7, passedCount: 6, failedCount: 1, eliminationRate: 14, avgDifficulty: 3.2 },
  ],
  2: [ // Microsoft
    { roundNumber: 1, roundType: 'Online Assessment', totalAttempts: 52, passedCount: 20, failedCount: 32, eliminationRate: 62, avgDifficulty: 3.4 },
    { roundNumber: 2, roundType: 'Technical Interview 1', totalAttempts: 20, passedCount: 11, failedCount: 9, eliminationRate: 45, avgDifficulty: 3.8 },
    { roundNumber: 3, roundType: 'Technical Interview 2', totalAttempts: 11, passedCount: 7, failedCount: 4, eliminationRate: 36, avgDifficulty: 4.2 },
    { roundNumber: 4, roundType: 'HR Interview', totalAttempts: 7, passedCount: 6, failedCount: 1, eliminationRate: 14, avgDifficulty: 2.5 },
  ],
  3: [ // Amazon
    { roundNumber: 1, roundType: 'Online Assessment', totalAttempts: 63, passedCount: 19, failedCount: 44, eliminationRate: 70, avgDifficulty: 3.8 },
    { roundNumber: 2, roundType: 'Technical Interview', totalAttempts: 19, passedCount: 10, failedCount: 9, eliminationRate: 47, avgDifficulty: 4.3 },
    { roundNumber: 3, roundType: 'Bar Raiser Interview', totalAttempts: 10, passedCount: 6, failedCount: 4, eliminationRate: 40, avgDifficulty: 4.7 },
  ],
};

// --- Readiness Analysis (mock) ---
export const readinessData: ReadinessAnalysis = {
  company: 'Google',
  companyId: 1,
  similarStudentsCount: 18,
  similarStudentsSuccessRate: 22.2,
  overallSuccessRate: 12.7,
  yourStrengths: [
    { topic: 'Arrays/Strings', yourScore: 8.2, targetScore: 7.5, status: 'STRONG' },
    { topic: 'CGPA', yourScore: 8.3, targetScore: 8.0, status: 'STRONG' },
  ],
  focusAreas: [
    { topic: 'Dynamic Programming', yourScore: 4.1, targetScore: 7.0, gap: 2.9, recommendation: 'Solve 30 more DP problems', prevalence: '73% of Round 1 questions' },
    { topic: 'Graphs', yourScore: 5.8, targetScore: 7.5, gap: 1.7, recommendation: 'Focus on: DFS, BFS, Shortest Path', prevalence: '65% of Round 1 questions involve graphs' },
  ],
  timeline: {
    avgPrepWeeks: 7,
    companyVisitInWeeks: 4,
    status: 'TIGHT',
  },
};

// --- Topics for multi-select ---
export const availableTopics = [
  'Dynamic Programming', 'Graphs', 'Trees', 'Arrays', 'Strings',
  'Hash Maps', 'Stacks', 'Queues', 'Heaps', 'Linked Lists',
  'Binary Search', 'Sorting', 'Greedy', 'Backtracking', 'Recursion',
  'System Design', 'OOP', 'Design Patterns', 'Databases', 'SQL',
  'OS', 'Networking', 'Machine Coding', 'Aptitude', 'Behavioral',
  'Probability', 'Mathematics', 'Bit Manipulation', 'Tries', 'Segment Trees',
];

// --- Round types ---
export const roundTypes = [
  'Online Assessment', 'Technical Interview', 'Technical Interview 1',
  'Technical Interview 2', 'Machine Coding', 'HR Interview',
  'Hiring Manager', 'Bar Raiser Interview', 'Group Discussion',
  'Case Study', 'System Design Round',
];
